### ISSUE TITLE
Center of Mass MSD 

### ISSUE THREAD

**Issue by EduardMock** [neujan/MDorado#6]
Since only Gromacs .tpr formats provide the needed information for center of mass calculation with the keyword "compound='molecules'", a seperate function for other file formats would be helpful.

**Comment by neujan** [comment]
Changed the keyword from compound="molecules" to compound="residues" in msd-module. This was already the case for the gofr-module.
Now the center-of-mass of atoms belonging to the same residue will be computed. This should fix the issue for most formats and simulations. Care should of cause be taken, when molecules are split over multiple residues.
